#!/usr/bin/env python3
#
# Grabs flags for teams to use with Ranking Web Server
#
# Made by Tudor Roman, public domain
#
# This script expects as its first argument a path to a csv file with two columns,
# name and id. name should be the long name of the team, like "Romania - Juniors",
# while id should be the acronym of the team
#

import csv
import sys
from subprocess import call

if len(sys.argv) != 2:
    print("Usage: add_teams <csv_file>")
    sys.exit(1)

with open(sys.argv[1]) as file:
    reader = csv.DictReader(file, delimiter=',')
    for row in reader:
        country = row['id'][0:2].lower()
        call(['wget', '-O', '{}.png'.format(row['id']), 'https://github.com/hjnilsson/country-flags/raw/master/png100px/{}.png'.format(country)])
        print(row['id'][0:2])
